// <auto-generated />
namespace MDIEFL2IAGE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class creatio_class_etud : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(creatio_class_etud));
        
        string IMigrationMetadata.Id
        {
            get { return "202501202232448_creatio_class_etud"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
